### ISSUE TITLE
"Db Default Value" property for entity fields

### ISSUE THREAD

**Issue by buchatsky** [msawczyn/EFDesigner2022#15]
**Proposed behaiour**
"Db Default Value" (or whatever) property in "Database" category for entity fields which would generate .HasDefaultValueSql(string) clause in DbContext.OnModelCreating() method. E.g. "(getdate())", "(newid())" or user-defined functions.
User scenarios:
- SQL scripts to update DB besides EF Migrations;
- importing data directly to DB

**Current behaviour**
Allows only initial values of the same type as field type. Doesn't allow string expressions.

**Versions**
EF Visual Editor: 4.1.2.0
Visual Studio 2022: 17.1.3

**Comment by BlackPuddingERP** [comment]
Hello! From what I have been able to verify, this behavior is currently not working. The value set in the "Database Default Value" is completely ignored. I have also observed that if you have an "Initial Value" established and set a value in "Database Default Value," this property becomes hidden, but when generating the model, it still takes into account the value that the property had before being hidden.

Currently, I have no way of setting DateTime.Now in a DateTime property because if I set "DateTime.Now" as the "Initial Value," it automatically sets it as the default value in the model's constructor signature and since it is a variable value and not a fixed one, it results in an error.

Thank you
