### ISSUE TITLE
Toolbox Items missing

### ISSUE THREAD

**Issue by devtrix** [msawczyn/EFDesigner2022#42]
In VS 2022, the toolbox items are missing. If I select Show All in the context menu, it shows the EFDiagrams but all the options are greyed out.

**Comment by msawczyn** [comment]
Visual studio toolbox items are finicky beasts. I've seen that problem occasionally as well. The biggest problem is that it's rarely the same root cause twice in a row, so a simple "just do this" answer doesn't work.

I've tucket away a few pages of discussion and things-to-try for when this happens. Luckily it's infrequent enough that I NEED to tuck these away, because I always forget what I did the last time that resolved it. The links are:

DevExpress info on fixing the toolbox when it goes bad after installing their tools
https://docs.devexpress.com/GeneralInformation/403588/support-debug-troubleshooting/visual-studio-toolbox

Pretty much the same, but from Zendesk
https://devdept.zendesk.com/hc/en-us/articles/217842718-Resetting-Toolbox-and-Clearing-the-Toolbox-Cache

Community discussion of things to do to fix toolbox issues
https://stackoverflow.com/questions/1268298/how-to-rebuild-the-visual-studio-toolbox

Hope these help.
