### ISSUE TITLE
Error when modifying a class property

### ISSUE THREAD

**Issue by rdeharo** [msawczyn/EFDesigner2022#59]
Hi, 
I am trying to modify a model with EF VISUAL EDITOR in VISUAL STUDIO 2022. 
It is only about modifying "Max length" in a property of a class. 
When I make the change and save the model, ef visual editor throws the following errors and fails to regenerate the code of the class"

![image](https://user-images.githubusercontent.com/69503553/224986742-528092ac-6577-4bda-aacb-3c29fd430aa4.png)

I have uninstalled and reinstalled EF VISUAL EDITOR but the error persists.

**Comment by MichaelSawczyn-AWH** [comment]
The error indicates it can't find various template (*.ttinclude) files, which should be in the install directory for the extension. 

Just to be safe, you're installing the extension at https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner2022, yes? Not the one at https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner, which is for Visual Studio 2019? 

If you're installing the correct extension, try to find where it installed. Depending on how you installed Visual Studio 2022, it could be in a different location, but the default is

C:\Program Files\Microsoft Visual Studio\2022\<SKU>\Common7\IDE\Extensions

where <SKU> is the type of Visual Studio you have. For example, I'm running Enterprise, so that directory is C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions. It could be "Community" or others, depending on what you have.

Under that directory is a bunch of other randomly named directories. Find the one that has Sawczyn.EFDesigner.EFModel.DslPackage.dll and look for the "TextTemplates" directory under it. You should see the following files:

- EF6ModelGenerator.ttinclude
- EFCore2ModelGenerator.ttinclude
- EFCore3ModelGenerator.ttinclude
- EFCore5ModelGenerator.ttinclude
- EFCoreModelGenerator.ttinclude
- EFDesigner.ttinclude
- EFModelFileManager.ttinclude
- EFModelGenerator.ttinclude
- MultipleOutputHelper.ttinclude
- VSIntegration.ttinclude

If they're not there, your installations are failing for some reason. You can copy those in from GitHub.

**Comment by msawczyn** [comment]
The error indicates it can't find various template (*.ttinclude) files, which should be in the install directory for the extension. 

Just to be safe, you're installing the extension at https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner2022, yes? Not the one at https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner, which is for Visual Studio 2019? 

If you're installing the correct extension, try to find where it installed. Depending on how you installed Visual Studio 2022, it could be in a different location, but the default is

C:\Program Files\Microsoft Visual Studio\2022\\[SKU]\Common7\IDE\Extensions

where [SKU] is the type of Visual Studio you have. For example, I'm running Enterprise, so that directory is C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions. It could be "Community" or others, depending on what you have.

Under that directory is a bunch of other randomly named directories. Find the one that has Sawczyn.EFDesigner.EFModel.DslPackage.dll and look for the "TextTemplates" directory under it. You should see the following files:

- EF6ModelGenerator.ttinclude
- EFCore2ModelGenerator.ttinclude
- EFCore3ModelGenerator.ttinclude
- EFCore5ModelGenerator.ttinclude
- EFCoreModelGenerator.ttinclude
- EFDesigner.ttinclude
- EFModelFileManager.ttinclude
- EFModelGenerator.ttinclude
- MultipleOutputHelper.ttinclude
- VSIntegration.ttinclude

If they're not there, your installations are failing for some reason. You can copy those in from GitHub.

**Comment by rdeharo** [comment]
Hi,
Yes I've installed the extension at https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner2022
The files are in the folder 
c:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Extensions\m3tta2ql.rdv\TextTemplates\

![image](https://user-images.githubusercontent.com/69503553/225014742-b29fef25-4f4d-42de-a395-63817730da0c.png)

**Comment by msawczyn** [comment]
Hmm. Quite a puzzle you have here.

Let's try something. Temporarily, add a copy of those files to your project, at the same directory level as your `.tt` file. Does it see them then?

**Comment by msawczyn** [comment]
Ah! I think I see the issue. What version of the designer are you running?

**Comment by msawczyn** [comment]
Hmm. That doesn't look right. It looks more like a `.ttinclude` file than the root `.tt` file.

That `.tt` file should start with
```
<#@ template inherits="Microsoft.VisualStudio.TextTemplating.VSHost.ModelingTextTransformation" debug="true"
             hostSpecific="true" language="C#" compilerOptions="/langversion:latest"#>
<#@ CleanupBehavior processor="T4VSHost" CleanupAfterProcessingtemplate="true" #>  
<#@ assembly name="System.Data.Entity.Design.dll" 
#><#@ assembly name="Microsoft.VisualStudio.Interop"
#><#@ include file="EFDesigner.ttinclude" once="true"
#><#@ output extension=".cs" 
#><#@ import namespace="System.Linq" 
#><#@ import namespace="System" 
#><#@ import namespace="System.Data.Entity.Design.PluralizationServices" 
#><#@ import namespace="System.Globalization" 
#><#@ import namespace="Sawczyn.EFDesigner.EFModel" 
#><#@ EFModel processor="EFModelDirectiveProcessor" requires="FileName='[model name].efmodel'"  
#><#
   Manager manager = Manager.Create(Host, GenerationEnvironment);
   manager.FileNameMarker = ModelRoot.FileNameMarker;
```
where `[model name]` is the name of your `.efmodel` file

Is this a new model you're starting?

**Comment by rdeharo** [comment]
Ah, ok, the .tt file start with 

<#@ template inherits="Microsoft.VisualStudio.TextTemplating.VSHost.ModelingTextTransformation" debug="true"
             hostSpecific="true" language="C#" compilerOptions="/langversion:latest"#>
<#@ CleanupBehavior processor="T4VSHost" CleanupAfterProcessingtemplate="true" #>  
<#@ assembly name="System.Data.Entity.Design.dll" 
#><#@ assembly name="EnvDTE"
#><#@ include file="MultipleOutputHelper.ttinclude" once="true"
#><#@ include file="VSIntegration.ttinclude" once="true"
#><#@ include file="EFDesigner.ttinclude" once="true"
#><#@ include file="EF6Designer.ttinclude" once="true"
#><#@ include file="EFCoreDesigner.ttinclude" once="true"
#><#@ output extension=".cs" 
#><#@ import namespace="System.Linq" 
#><#@ import namespace="System" 
#><#@ import namespace="System.Data.Entity.Design.PluralizationServices" 
#><#@ import namespace="System.Globalization" 
#><#@ import namespace="Sawczyn.EFDesigner.EFModel" 
#><#@ EFModel processor="EFModelDirectiveProcessor" requires="FileName='Sepadron.efmodel'"  
#><#
   Manager manager = Manager.Create(Host, GenerationEnvironment);
   manager.FileNameMarker = ModelRoot.FileNameMarker;

The model is not a new model. It is a model that had not been edited for some time.

**Comment by msawczyn** [comment]
Ok, so try replacing those lines with the ones in the prior message. Things have changed (they're documented in the main readme for this repo) and you unfortunately ran into a defect that slipped in to the version you're using.

Don't forget to leave the "processor" line to what you currently have. That's where the .tt gets told what the model file is. To be clear, those lines should read
```
<#@ template inherits="Microsoft.VisualStudio.TextTemplating.VSHost.ModelingTextTransformation" debug="true"
             hostSpecific="true" language="C#" compilerOptions="/langversion:latest"#>
<#@ CleanupBehavior processor="T4VSHost" CleanupAfterProcessingtemplate="true" #>  
<#@ assembly name="System.Data.Entity.Design.dll" 
#><#@ assembly name="Microsoft.VisualStudio.Interop"
#><#@ include file="EFDesigner.ttinclude" once="true"
#><#@ output extension=".cs" 
#><#@ import namespace="System.Linq" 
#><#@ import namespace="System" 
#><#@ import namespace="System.Data.Entity.Design.PluralizationServices" 
#><#@ import namespace="System.Globalization" 
#><#@ import namespace="Sawczyn.EFDesigner.EFModel" 
#><#@ EFModel processor="EFModelDirectiveProcessor" requires="FileName='Sepadron.efmodel'"
#><#
   Manager manager = Manager.Create(Host, GenerationEnvironment);
   manager.FileNameMarker = ModelRoot.FileNameMarker;
```
