### ISSUE TITLE
Table names are pluralized even when flag set to false

### ISSUE THREAD

**Issue by Olivercomputing** [msawczyn/EFDesigner2022#65]
In the properties for the entire model, in the Database section, there's a Pluralize Table Names property. Table names are create as plural even when this is set to false.

**Comment by msawczyn** [comment]
Are you using an English language version of Visual Studio? That feature is dependent on the Microsoft Pluralization Service, which may or may not be implemented depending on the language version. 

Now that you bring that up, though, I will make that setting unavailable if the tool detects the service is not present.

If you are using the English version (or some other version where it's implemented), I'll have more digging to do, because I can't reproduce that problem in my installation.
