### ISSUE TITLE
Unable to drag/drop or add a relation in the Designer

### ISSUE THREAD

**Issue by Retidurc** [msawczyn/EFDesigner2022#73]
Hello ! I'm using EFDesigner 4.2.5.1 on Visual studio 2022 17.6.5

I'm a simply unable to drag and drop any relation(unidirectional,bidirectional, or inheritance, event comment link don't work) from the toolbox, into any entity. I only get the "cancel" cursor, and can't do anything.

I may be trying to use the tool in a wrong way: I try to drag the relation, onto the entity. 

I tried to see if contextual menu on entities proposes to add a relation in any other way, but didn't find anything.

Am I doing something wrong or is the designer not working with the last visual studio ?

**Comment by BlackPuddingERP** [comment]
Hello @Retidurc,

Perhaps it's a bit confusing because no difference is apparent between the entities and relationships that I specified, in terms of how to add them to the designer. Regarding the relationships, you don't have to drag and drop them onto the entity; you need to click on them and they will become selected. Then you have to go to the entity that would be the 'one' part of the 1:n relationship and click on it, and then proceed to click on the entity that represents the 'many' part.

I hope this is helpful to you.

Regards

**Comment by Retidurc** [comment]
Oh thanks.

Duh. I feel kinda dumb . I'm used to drag and drop items from the toolbox in other kind of designers. I tried everything except what you just told me. I've spent half an hour reading the online doc of this project and didn't found any clue on how to exactly do what you just told me.
That's why I was thinking I didn't found something that was obvious to everyone else :rofl: .

Not blaming anyone here on the project, that's an awesome tool and all ! Sometimes I just miss the obvious :neutral_face: 
If the docs are open and can be modified, I'll add something nonetheless. I suspect I may not be the only guy who struggled with something that obvious. 

Thanks again !
