### ISSUE TITLE
Update to Visual Studio 2022 Version 17.8.5 stops EF Visual Designer from the .efmodel file

### ISSUE THREAD

**Issue by amplifiedart** [msawczyn/EFDesigner2022#92]
Hi, first of all thank you for simplifying our table design tasks to a more common graphical designer, I have been using it within some Proof of concept applications and it seems that it will stay within my development workflow. 

### Isue
The issue encountered is when I update Visual Studio 2022 (I have two installations with the same results) as soon as I updated to version 17.8.5 double-clicking the .efmodel file Visual Studio comes into a "not-responding" state and does not recover. 

I have approached it differently on both systems:

1. First System first update Visual Studio to version 17.8.5, old EF Visual Designer did not open the .efmodel, thereafter updated your Extension with the same results
2. Checked the VS version first (17.8.4) all was operational, updated the Visual Designer to the latest which was still operational. Update visual studio to the 17.8.5 version which broke the extension.

Version 17.8.5 was needed as it updated the autocomplete within Blazor development.
Hope you can assist.

Regards,
Arjo.

**Comment by Opzet** [comment]
Hi Arjo,

Just saw this,  and *phew* realised I am not having the issue because lucky me I have 'Automatically update this extension' turned off.

If it helps and your stuck, you can roll back Entity Framework Visual Editor, I have several Developer Installations of Visual Studio 17.8.5  working with Entity Framework Visual Editor version 4.2.5.1 (19/08/2023) 

Download links:
-- Old Entity Framework Visual Editor 4.2.5.1 19/8/23 --
[https://marketplace.visualstudio.com/_apis/public/gallery/publishers/michaelsawczyn/vsextensions/EFDesigner2022/4.2.5.1/vspackage]

-- Latest Entity Framework Visual Editor 4.2.7.3 [@27/1/23] -- https://marketplace.visualstudio.com/_apis/public/gallery/publishers/michaelsawczyn/vsextensions/EFDesigner2022/4.2.7.3/vspackage

**Comment by amplifiedart** [comment]
Dear David,

Thanks for your reply, I have downgraded the extension and were not directly able to use the extension on an old solution. I created a new solution with a new model, which went fine, afterwards I opened the old solution and was able to use the designer without any issues. Hope this helps. 

Happy coding 👍 

Kind Regards,
Arjo.
